apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        args: [ "--smallfiles" ]
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name:  mongo-persistent-storage
          persistentVolumeClaim:
            claimName: sample-pvc
