apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
