# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "rake"

# development
group :development do
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rake", require: false
  gem "rubocop-sequel", require: false
end