name: pip check
on:
  pull_request:
    branches:
      - main
    paths:
      - "python/gpt-codegen/**"

jobs:
  pip-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: pip check
        run: |
          pip install -r requirements.txt
        working-directory: python/gpt-codegen

