name: pip check
on:
  pull_request:
    branches:
      - main

jobs:
  pip-check:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'python/gpt-codegen/**'

      # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'true'
        run: |
          pip install -r requirements.txt && pip check
        working-directory: python/gpt-codegen

