name: reviewdog golangci-lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'go/**'

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./go

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          reviewdog_flags: -name="golangci lint"
