name: issue validator
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Okabe-Junya/issue-validator@v0.4.1
        with:
          title: '^TEST'
          title-regex-flags: 'true'
          is-auto-close: 'false'
          issue-type: 'issue'
          github-token: ${{ secrets.GITHUB_TOKEN }}
