name: issue validator
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Okabe-Junya/issue-validator@v0.2.5
        with:
          title: 'test'
          is-auto-close: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
