name: Issue metrics
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$last_day"
          echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

      - name: Get issue metrics (repo1)
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:Okabe-Junya/sandbox is:issue created:${{ env.last_month }} -reason:"not planned"'

      - name: Copy issue metrics (repo1)
        run: |
          cp ./issue_metrics.md ./issue_metrics_repo1.md

      - name: Get issue metrics (repo2)
        uses: github/issue-metrics@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:Okabe-Junya/dotfiles is:issue created:${{ env.last_month }} -reason:"not planned"'

      - name: Copy issue metrics (repo2)
        run: |
          cp ./issue_metrics.md ./issue_metrics_repo2.md

      - name: Merge issue metrics
        run: |
          chmod 700 ./issue_metrics.md
          echo "## repo1" >> ./issue_metrics.md
          cat ./issue_metrics_repo1.md > ./issue_metrics.md
          echo "## repo2" >> ./issue_metrics.md
          cat ./issue_metrics_repo2.md >> ./issue_metrics.md

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Monthly issue metrics report (dev)
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: Okabe-Junya
