name: Rspec Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "ruby/ci-sample/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby/ci-sample
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
