name: Rspec Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "ruby/ci-sample/**"

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby/ci-sample
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: ruby/ci-sample

  test:
    runs-on: ubuntu-latest
    needs: dependency-check
    defaults:
      run:
        working-directory: ruby/ci-sample
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: ruby/ci-sample

      - name: Run tests
        run: bundle exec rake
