name: reviewdog rubocop

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
    paths:
      - "ruby/**"
permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: runner / rubocop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ruby
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-review
          workdir: ruby/ci-sample
          reviewdog_flags: -name="rubocop reviewdog"
